import { IProduct } from "../interface";
export const Products: IProduct[] = [
  {
    id: "1",
    isFav: true,
    name: "Acheron",
    image: "/src/assets/test_image/acheron_01.jpg",
    price: 100,
    sold: 20,
  },
  {
    id: "2",
    isFav: true,
    name: "BlackSwan",
    image: "/src/assets/test_image/blackswan_01.jpg",
    price: 200,
    sold: 20,
  },
  {
    id: "3",
    isFav: true,
    name: "Hanabi",
    image: "/src/assets/test_image/hanabi_01.jpg",
    price: 300,
    sold: 20,
  },
  {
    id: "4",
    isFav: false,
    name: "Robin",
    image: "/src/assets/test_image/robin_01.jpg",
    price: 50,
    sold: 20,
  },
  {
    id: "5",
    isFav: false,
    name: "Stelle",
    image: "/src/assets/test_image/stelle_01.jpg",
    price: 20,
    sold: 20,
  },
  {
    id: "6",
    isFav: true,
    name: "Acheron",
    image: "/src/assets/test_image/acheron_01.jpg",
    price: 1999,
    sold: 20,
  },
  {
    id: "7",
    isFav: true,
    name: "BlackSwan",
    image: "/src/assets/test_image/blackswan_01.jpg",
    price: 2199,
    sold: 20,
  },
  {
    id: "8",
    isFav: true,
    name: "Hanabi",
    image: "/src/assets/test_image/hanabi_01.jpg",
    price: 2299,
    sold: 20,
  },
  {
    id: "9",
    isFav: false,
    name: "Robin",
    image: "/src/assets/test_image/robin_01.jpg",
    price: 3999,
    sold: 20,
  },
  {
    id: "10",
    isFav: false,
    name: "Stelle",
    image: "/src/assets/test_image/stelle_01.jpg",
    price: 3999,
    sold: 20,
  },
];
