import { IProduct } from "../interface";
export const Products: IProduct[] = [
  {
    id: "1",
    isFav: true,
    name: "Acheron",
    image: "https://picsum.photos/500",
    price: 100,
    sold: 20,
    category: "cpu",
  },
  {
    id: "2",
    isFav: true,
    name: "BlackSwan",
    image: "https://picsum.photos/501",
    price: 200,
    sold: 20,
    category: "mainboard",
  },
  {
    id: "3",
    isFav: true,
    name: "Hanabi",
    image: "https://picsum.photos/502",
    price: 300,
    sold: 20,
    category: "cpu",
  },
  {
    id: "4",
    isFav: false,
    name: "Robin",
    image: "https://picsum.photos/503",
    price: 50,
    sold: 20,
    category: "mainboard",
  },
  {
    id: "5",
    isFav: false,
    name: "Stelle",
    image: "https://picsum.photos/504",
    price: 20,
    sold: 20,
    category: "cpu",
  },
  {
    id: "6",
    isFav: true,
    name: "Acheron",
    image: "https://picsum.photos/505",
    price: 1999,
    sold: 20,
    category: "mainboard",
  },
  {
    id: "7",
    isFav: true,
    name: "BlackSwan",
    image: "https://picsum.photos/506",
    price: 2199,
    sold: 20,
    category: "cpu",
  },
  {
    id: "8",
    isFav: true,
    name: "Hanabi",
    image: "https://picsum.photos/507",
    price: 2299,
    sold: 20,
    category: "mainboard",
  },
  {
    id: "9",
    isFav: false,
    name: "Robin",
    image: "https://picsum.photos/508",
    price: 3999,
    sold: 20,
    category: "cpu",
  },
  {
    id: "10",
    isFav: false,
    name: "Stelle",
    image: "https://picsum.photos/509",
    price: 3999,
    sold: 20,
    category: "mainboard",
  },
];
